version: '3.4'

services:
  starterkit:
    image: ${DOCKER_REGISTRY}starterkit
    build:
      context: StarterPack
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_HTTPS_PORT: 55334
    ports:
      - "55334:80"
      - "44392:443"
    volumes:
      - ${APPDATA}\ASP.NET\Https:/root/.aspnet/https:ro
      - ${APPDATA}\Microsoft\UserSecrets\${USER_SECRETS_ID}:/root/.microsoft/usersecrets/${USER_SECRETS_ID}:ro
      - ${PROJECT_PATH}\StarterPack:/app