version: '3.4'

services:
  starterkit:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=44392
    ports:
      - "55334:80"
    volumes:
      - ${APPDATA}\ASP.NET\Https:/root/.aspnet/https:ro
      - ${APPDATA}\Microsoft\UserSecrets\${USER_SECRETS_ID}:/root/.microsoft/usersecrets/${USER_SECRETS_ID}:ro
